### ISSUE TITLE
The data layer structure in prototxt of mobilenet ?

### ISSUE THREAD

**Issue by binbinmeng** [HolmesShuan/Caffe-Computation-Graph-Optimization#1]
if the structure is :
 input: "data"
 input_dim: 1
 input_dim: 3
 input_dim: 224
 input_dim: 224
it will show errors:
F1027 21:35:14.673329 30523 insert_splits.cpp:29] Unknown bottom blob 'data' (layer 'conv1/7x7_s2', bottom index 0)

**Comment by HolmesShuan** [comment]
```proto
layer {
  name: "data"
  type: "Input"
  top: "data"
  input_param { shape: { dim: 1 dim: 3 dim: 224 dim: 224 } }
}
```

**Comment by binbinmeng** [comment]
Thanks very much !
